# Generated by Django 3.2.4 on 2021-06-20 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='accounts',
            field=models.ManyToManyField(related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунты'),
        ),
        migrations.AddField(
            model_name='contact',
            name='hide_for',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Скрыть для'),
        ),
    ]
