# Generated by Django 3.2.4 on 2021-06-20 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунты'),
        ),
    ]
