# Generated by Django 3.2.4 on 2021-06-26 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contacts.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type_payment',
            field=models.IntegerField(choices=[(0, 'Debt'), (1, 'Paid')], null=True, verbose_name='Тип оплаты'),
        ),
    ]
